### ISSUE TITLE
aliyun-v0.26.1 是不是没有Build成功？

### ISSUE THREAD

**Issue by edwardhey** [AliyunContainerService/minikube#1]
**What happened**:
RT.
**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by denverdino** [comment]
我这边没有问题，有详细信息吗？

**Comment by edwardhey** [comment]
https://github.com/AliyunContainerService/minikube/branches

下载更新后，minikube的内pod的ip还是10.0.的 不是10.96. 然后内置的几个pod下载镜像不是阿里的，下载速度比较慢

> go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/edwardhey/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/opt/local/go:/mnt/xvdb/Projects/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fp/ltwplqgs0l1c4__5xwdht6140000gn/T/go-build349463180=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by denverdino** [comment]
0.26开始已经换用kubeadm来配置Minikube，这个方式与localkube方式相比启动速度较慢，但是好处是兼容性更好。
所有Pod下载应该都已经调整过了，我日常也在用。如果有遗漏特此告知

**Comment by edwardhey** [comment]
多谢多谢

**Comment by edwardhey** [comment]
Failed to pull image "registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-dns-sidecar-amd64:1.14.8": rpc error: code = Canceled desc = context canceled
Liveness probe failed: Get http://172.17.0.3:10054/healthcheck/dnsmasq: dial tcp 172.17.0.3:10054: getsockopt: connection refused

**Comment by denverdino** [comment]
感觉是网络问题？是否有公网连接？是否可以重现？

**Comment by edwardhey** [comment]
可以的，用回v0.25.2 了 下一个版本再试试看，多谢关注
