### ISSUE TITLE
如何在minikube start 中正常执行kubeadm init phase certs all --config /var/lib/kubeadm.yaml

### ISSUE THREAD

**Issue by sun-wenming** [AliyunContainerService/minikube#10]
## 执行 sudo minikube start --vm-driver=none --registry-mirror=https://registry.docker-cn.com
mecm@ubuntu:/home/ub$ sudo minikube start --vm-driver=none --registry-mirror=https://registry.docker-cn.com

😄  minikube v0.35.0 on linux (amd64)

🤹  Configuring local host environment ...

⚠️  The 'none' driver provides limited isolation and may reduce system security and reliability.
⚠️  For more information, see:
👉  https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

⚠️  kubectl and minikube configuration will be stored in /home/mecm
⚠️  To use kubectl or minikube commands as your own user, you may
⚠️  need to relocate them. For example, to overwrite your own settings:

    ▪ sudo mv /home/mecm/.kube /home/mecm/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running none VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.230.128
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.13.4 ...
🔄  Relaunching Kubernetes v1.13.4 using kubeadm ... 

   ============此处报错
💣  Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: exit status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

## 报错为执行 sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml
mecm@ubuntu:/home/ub$ **sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml**
W0321 12:15:28.120910   38639 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1alpha3", Kind:"InitConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "imageRepository"
[certs] Using certificateDir folder "/var/lib/minikube/certs/"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
error execution phase certs/apiserver-kubelet-client: [certs] certificate apiserver-kubelet-client not signed by CA certificate ca: crypto/rsa: verification error

## 删除此  --config /var/lib/kubeadm.yaml 正常执行. 
mecm@ubuntu:/home/ub$ sudo kubeadm init phase certs all
  [certs] Using certificateDir folder "/etc/kubernetes/pki"
  [certs] Using existing ca certificate authority
  [certs] Using existing apiserver-kubelet-client certificate and key on disk
  [certs] Using existing apiserver certificate and key on disk
  [certs] Using existing etcd/ca certificate authority
  [certs] Using existing etcd/server certificate and key on disk
  [certs] Using existing etcd/peer certificate and key on disk
  [certs] Using existing etcd/healthcheck-client certificate and key on disk
  [certs] Using existing apiserver-etcd-client certificate and key on disk
  [certs] Using existing front-proxy-ca certificate authority
  [certs] Using existing front-proxy-client certificate and key on disk
  [certs] Using the existing "sa" key

期待您的答复。谢谢。

**Comment by denverdino** [comment]
Fixed, thanks for providing details. Pls get the latest binary and test again
