### ISSUE TITLE
minikube报404

### ISSUE THREAD

**Issue by qing-root** [AliyunContainerService/minikube#103]
**重现问题所需的命令**：
下载：curl -Lo minikube https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/releases/v1.18.1/minikube-linux-arm64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
安装启动：
sudo minikube start --image-mirror-country=cn --registry-mirror=https://kaakiyao.mirror.aliyuncs.com --kubernetes-version=1.18.1 --vm-driver=none

**失败的命令的完整输出**：<details>
![image](https://user-images.githubusercontent.com/30001685/169360735-cef9f8b9-71d6-402c-9376-f3c7ec26c1f4.png)
校验地址直接报404
`Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubelet: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.1/bin/linux/arm64/kubelet?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.1/bin/linux/arm64/kubelet.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.1/bin/linux/arm64/kubelet?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.1/bin/linux/arm64/kubelet.sha256 Dst:/root/.minikube/cache/linux/v1.18.1/kubelet.download Pwd: Mode:2 Umask:---------- Detectors:[0x26bc460 0x26bc460 0x26bc460 0x26bc460 0x26bc460 0x26bc460 0x26bc460] Decompressors:map[bz2:0x26bc460 gz:0x26bc460 tar.bz2:0x26bc460 tar.gz:0x26bc460 tar.xz:0x26bc460 tbz2:0x26bc460 tgz:0x26bc460 txz:0x26bc460 xz:0x26bc460 zip:0x26bc460] Getters:map[file:0x4001074060 http:0x4001038000 https:0x4001038020] Dir:false ProgressListener:0x2681b10 Options:[0xa3cba0]}: invalid checksum: Error downloading checksum file: bad response code: 404
`
</details>

**`minikube logs`命令的输出**： <details>
无

</details>

**使用的操作系统版本**：

**Comment by denverdino** [comment]
我看了一下没有 1.18.1 版本，建议用 v1.18.20 版本
