### ISSUE TITLE
Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

### ISSUE THREAD

**Issue by CzyerChen** [AliyunContainerService/minikube#13]
Mac with minikube version: v1.1.0
after running qinikube start, then showing the info below

😄  minikube v1.1.0 on darwin (amd64)
✅  using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0612 19:40:14.748221    9489 start.go:529] StartHost: create: precreate: exit status 126

💣  Unable to start VM: create: precreate: exit status 126

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

So what is wrong ? Is there any setting should be done on Mac  ?

**Comment by saintube** [comment]
This issue was mentioned [here](https://github.com/kubernetes/minikube/issues/1655).

**Comment by denverdino** [comment]
@saintube Thanks
