### ISSUE TITLE
页面文章访问失败（有最新版的aliyun-minikube地址吗）

### ISSUE THREAD

**Issue by 99Kies** [AliyunContainerService/minikube#18]
1. < https://yq.aliyun.com/articles/221687 >
××访问失败××

**Comment by denverdino** [comment]
参考这个吧 https://github.com/AliyunContainerService/minikube/wiki

**Comment by denverdino** [comment]
估计是在人工审核

**Comment by 99Kies** [comment]
> 估计是在人工审核

thanks 🤭
