### ISSUE TITLE
master分支下的: pkg/minikube/translate下面和官方库对比是不是少了个translations.go文件

### ISSUE THREAD

**Issue by usernameisnull** [AliyunContainerService/minikube#21]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by denverdino** [comment]
master 分支我一般不动，只会在branch分支上修复

**Comment by usernameisnull** [comment]
OK,懂了
