### ISSUE TITLE
把storage.googleapis.com类似的网址的资源都移到国内如何?

### ISSUE THREAD

**Issue by usernameisnull** [AliyunContainerService/minikube#22]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：
方便么?

**Comment by denverdino** [comment]
太大了😅有什么具体需求吗？我已经同步了minikube所需的内容

**Comment by usernameisnull** [comment]
> 太大了😅有什么具体需求吗？我已经同步了minikube所需的内容

比如kubeadm,kubectl,kubelet这些(还有iso等),第一次的时候还是通过storage.googleapis.com去下载的, 不挂代理真是下半天

**Comment by denverdino** [comment]
您是用的哪个分支？我看看

**Comment by usernameisnull** [comment]
> 您是用的哪个分支？iso应该移动了，kubeadm,kubectl,kubelet这些我想想怎么办

aliyun-v1.11.0

**Comment by denverdino** [comment]
地址在这些位置

http://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.5/bin/linux/amd64/kubectl
http://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.5/bin/linux/amd64/kubeadm
http://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.5/bin/darwin/amd64/kubectl

**Comment by denverdino** [comment]
Fixed more in aliyun-v1.12.0, pls try again. thanks
