### ISSUE TITLE
这个url报404了

### ISSUE THREAD

**Issue by usernameisnull** [AliyunContainerService/minikube#24]
**重现问题所需的命令**：
./out/minikube start --image-mirror-country cn     --iso-url=https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.5.1.iso     --registry-mirror=https://xxxx.mirror.aliyuncs.com     --kubernetes-version=v1.16.2     --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers     --vm-driver=none --log_dir='/var/log/minikube' --alsologtostderr >/tmp/1.txt 2>&1
**失败的命令的完整输出**：
<details>

</details>

**`minikube logs`命令的输出**： <details>

W0701 16:53:10.062060   83159 preload.go:112] http://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v3-v1.16.2-docker-overlay2-amd64.tar.lz4 status code: 404
</details>

**使用的操作系统版本**：
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by denverdino** [comment]
有些版本没有的，尽量用比较新的版本吧 比如 1.16.11 或 1.16.12
