### ISSUE TITLE
无法启动minikube

### ISSUE THREAD

**Issue by huowolf** [AliyunContainerService/minikube#25]
**重现问题所需的命令**：
minikube start --registry-mirror=https://fgi18ddn.mirror.aliyuncs.com --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --vm-driver=none  --base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10

**失败的命令的完整输出**：<details>
[root@localhost ~]# minikube start --registry-mirror=https://fgi18ddn.mirror.aliyuncs.com --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --vm-driver=none  --base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10
* Centos 7.6.1810 上的 minikube v1.11.0
* 根据现有的配置文件使用 none 驱动程序
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is CentOS Linux 7 (Core)
* 正在 Docker 19.03.12 中准备 Kubernetes v1.18.3…
    > kubelet.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubectl.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm: 37.97 MiB / 37.97 MiB [-----------] 100.00% 297.79 KiB p/s 2m11s
    > kubelet: 108.04 MiB / 108.04 MiB [---------] 100.00% 762.23 KiB p/s 2m25s
* 
X 更新 cluster 失败: updating node: downloading binaries: downloading kubectl: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubectl.sha256: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubectl.sha256 Dst:/root/.minikube/cache/linux/v1.18.3/kubectl.download Pwd: Mode:2 Detectors:[0x28a9e40 0x28a9e40 0x28a9e40 0x28a9e40 0x28a9e40 0x28a9e40] Decompressors:map[bz2:0x28a9e40 gz:0x28a9e40 tar.bz2:0x28a9e40 tar.gz:0x28a9e40 tar.xz:0x28a9e40 tbz2:0x28a9e40 tgz:0x28a9e40 txz:0x28a9e40 xz:0x28a9e40 zip:0x28a9e40] Getters:map[file:0xc0005d32f0 http:0xc000583da0 https:0xc000583dc0] Dir:false ProgressListener:0x2882f30 Options:[0xc160f0]}: Checksums did not match for /root/.minikube/cache/linux/v1.18.3/kubectl.download.
Expected: 6fcf70aae5bc64870c358fac153cdfdc93f55d8bae010741ecce06bb14c083ea
Got: 94105a5eca0ccd4de3b27221f806694fd56f439c60f7aa8e715a8f29304686f8
*sha256.digest
* 
* 由于出错 minikube 正在退出。如果以上信息没有帮助，请提交问题反馈：
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs`命令的输出**： <details>
* The control plane node must be running for this command
  - To fix this, run: "minikube start"

</details>

**使用的操作系统版本**：
centos 7.6.1810

**Comment by denverdino** [comment]
Try aliyun-v1.12.0
