### ISSUE TITLE
启动时 save image 失败

### ISSUE THREAD

**Issue by matrixback** [AliyunContainerService/minikube#26]
**重现问题所需的命令**：
minikube start --driver=docker
**失败的命令的完整输出**：<details>
save image to file "registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.18.3" -> "/Users/matrix/.minikube/cache/images/registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy_v1.18.3" failed: write: unexpected EOF

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：
macOS

**Comment by denverdino** [comment]
是哪个版本，我试验了阿里云修改的v1.12.1版本，没有问题

```
$ minikube start --driver=docker

😄  Darwin 10.15.5 上的 minikube v1.12.1
✨  根据用户配置使用 docker 驱动程序
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=1990MB) ...
🐳  正在 Docker 19.03.2 中准备 Kubernetes v1.18.3…
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  完成！kubectl 已经配置至 "minikube"

$ minikube dashboard

🔌  正在开启 dashboard ...
🤔  正在验证 dashboard 运行情况 ...
🚀  Launching proxy ...
🤔  正在验证 proxy 运行状况 ...
🎉  Opening http://127.0.0.1:52974/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ in your default browser...
```

**Comment by denverdino** [comment]
感觉是网络问题，请运行如下命令并排查？

`docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.18.3`

**Comment by matrixback** [comment]
太忙了，没有关注。今天试了两个版本，都不行，v1.23.9，v1.12.1 还是报 `20 19:02:42.546558   48400 cache.go:63] save image to file "registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v1.8.1" -> "/Users/xxxx/.minikube/cache/images/registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner_v1.8.1" failed: write: unexpected EOF`错误。
网络正常，上面你发的镜像可以获取到。

**Comment by denverdino** [comment]
是不是配置了代理？无法网络访问啊

```
docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v1.8.1
v1.8.1: Pulling from google_containers/storage-provisioner
d9770ba67fb2: Pull complete
Digest: sha256:088daa9fcbccf04c3f415d77d5a6360d2803922190b675cb7fc88a9d2d91985a
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v1.8.1
registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v1.8.1
```
