### ISSUE TITLE
`minikube start`时， `save image` 报错：`write: unexpected EOF`

### ISSUE THREAD

**Issue by youzipi** [AliyunContainerService/minikube#29]
**重现问题所需的命令**：
```
minikube start --memory='4g' --kubernetes-version=v1.16.5 --image-mirror-country='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers' 
```
看了 #26  这个，尝试 `docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.16.5`，是可以成功下载的。

2020-08-24 14:06:08
又试了下 `docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.16.5`
不稳定重现：
![image](https://user-images.githubusercontent.com/5629307/91009524-53a04180-e613-11ea-9142-4d6f847804b5.png)

2020-08-24 14:24:07
换了 aliyun 的版本 (` https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/releases/v1.12.3/minikube-darwin-amd64`)，还是一样的报错。

**失败的命令的完整输出**：<details>
```
😄  minikube v1.12.3 on Darwin 10.13.6
🆕  Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3
✨  Using the docker driver based on existing profile
❗  You cannot change the memory size for an exiting minikube cluster. Please first delete the cluster.
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
E0824 11:33:45.325384   85399 cache.go:63] save image to file "registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.16.5" -> "/Users/mac/.minikube/cache/images/registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler_v1.16.5" failed: write: unexpected EOF
E0824 11:34:39.549663   85399 cache.go:63] save image to file "registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.16.5" -> "/Users/mac/.minikube/cache/images/registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy_v1.16.5" failed: write: unexpected EOF
```
</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：
macOS 10.13.6

minikube version: v1.12.3
（minikube repo release 里面下载的）

**Comment by denverdino** [comment]
这个问题看起来是网络问题，就是连接阿里云镜像服务的时候网络不稳定，排查一下是否有proxy等影响。

**Comment by matrixback** [comment]
解决了没有呢？

**Comment by youzipi** [comment]
> 解决了没有呢？

没在用这个镜像地址了，改用给 minikube 配代理 去解决了。

**Comment by denverdino** [comment]
> 解决了没有呢？

这个问题没有的，gcr.io最近也有一些镜像策略调整，已经全部修复了

**Comment by Shirman** [comment]
同样是这个问题

**Comment by denverdino** [comment]
那个版本？
