### ISSUE TITLE
minikube v0.28.1 kube-dns 拉取镜像失败

### ISSUE THREAD

**Issue by MicroIdea** [AliyunContainerService/minikube#3]
Failed to pull image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.8": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
似乎是没有用阿里的源

 Ubuntu 18.04 桌面版，操作步骤:

1. curl -Lo minikube http://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/releases/v0.28.1/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

2. minikube start --registry-mirror=https://registry.docker-cn.com --logtostderr --loglevel 0
 
3. minikube dashborad

发现 kube-dns 没有部署成功

**Comment by denverdino** [comment]
Fixed,  pls download the minikube 0.28.1 and try again

**Comment by MicroIdea** [comment]
Yeah, fixed. Thanks
