### ISSUE TITLE
请问minikube start错误，多个版本都无法运行

### ISSUE THREAD

**Issue by shiguanghuxian** [AliyunContainerService/minikube#30]
**重现问题所需的命令**：minikube start --registry-mirror=https://zw6f10y7.mirror.aliyuncs.com --driver=none

**失败的命令的完整输出**：<details>
😄  Centos 7.4.1708 上的 minikube v1.13.0
✨  根据用户配置使用 none 驱动程序
👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=4, Memory=3790MB, Disk=44698MB) ...
ℹ️  OS release is CentOS Linux 7 (Core)
🐳  正在 Docker 19.03.12 中准备 Kubernetes v1.19.0…
    > kubeadm.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubelet.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubectl.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubectl: 10.85 MiB / 41.01 MiB [--->_________] 26.46% 3.65 MiB p/s ETA 8s❗  This bare metal machine is having trouble accessing https://registry.cn-hangzhou.aliyuncs.com/google_containers
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
    > kubectl: 41.01 MiB / 41.01 MiB [---------------] 100.00% 1.07 MiB p/s 39s
    > kubeadm: 37.30 MiB / 37.30 MiB [-------------] 100.00% 848.16 KiB p/s 46s
    > kubelet: 104.88 MiB / 104.88 MiB [-----------] 100.00% 1.43 MiB p/s 1m13s

❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubelet: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubelet?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubelet.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubelet?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubelet.sha256 Dst:/root/.minikube/cache/linux/v1.19.0/kubelet.download Pwd: Mode:2 Detectors:[0x2ac4bc0 0x2ac4bc0 0x2ac4bc0 0x2ac4bc0 0x2ac4bc0 0x2ac4bc0] Decompressors:map[bz2:0x2ac4bc0 gz:0x2ac4bc0 tar.bz2:0x2ac4bc0 tar.gz:0x2ac4bc0 tar.xz:0x2ac4bc0 tbz2:0x2ac4bc0 tgz:0x2ac4bc0 txz:0x2ac4bc0 xz:0x2ac4bc0 zip:0x2ac4bc0] Getters:map[file:0xc00067e4b0 http:0xc000503060 https:0xc000503080] Dir:false ProgressListener:0x2a8f4e0 Options:[0xc7baf0]}: Checksums did not match for /root/.minikube/cache/linux/v1.19.0/kubelet.download.
Expected: 3f03e5c160a8b658d30b34824a1c00abadbac96e62c4d01bf5c9271a2debc3ab
Got: 856c24d83e8a374a03e61c6e006462943936c17dda9459d8caf4024e27ff4304
*sha256.digest

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs`命令的输出**： <details>

🤷  The control plane node must be running for this command
👉  To fix this, run: "minikube start"
</details>

**使用的操作系统版本**：CentOS 7

**Comment by shiguanghuxian** [comment]
💣  更新 cluster 失败: updating control plane: downloading binaries: downloading kubelet: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubelet?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubelet.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubelet?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubelet.sha256 Dst:/root/.minikube/cache/linux/v1.18.3/kubelet.download Pwd: Mode:2 Detectors:[0x2ac7480 0x2ac7480 0x2ac7480 0x2ac7480 0x2ac7480 0x2ac7480] Decompressors:map[bz2:0x2ac7480 gz:0x2ac7480 tar.bz2:0x2ac7480 tar.gz:0x2ac7480 tar.xz:0x2ac7480 tbz2:0x2ac7480 tgz:0x2ac7480 txz:0x2ac7480 xz:0x2ac7480 zip:0x2ac7480] Getters:map[file:0xc00028c070 http:0xc0009be060 https:0xc0009be080] Dir:false ProgressListener:0x2a91d40 Options:[0xc76790]}: Checksums did not match for /root/.minikube/cache/linux/v1.18.3/kubelet.download.
Expected: 6aac8853028a4f185de5ccb5b41b3fbd87726161445dee56f351e3e51442d669
Got: c470dcd8d9d8168b8407a6203df436d8340af2f1ac8ce60a576ebb9b9956a638
*sha256.digest

**Comment by shiguanghuxian** [comment]
也可能出现这个错误，不晓得为啥

**Comment by denverdino** [comment]
您的网络排查一下，我的测试是没有问题的

```
 minikube start --registry-mirror=https://zw6f10y7.mirror.aliyuncs.com --driver=none
😄  Centos 8.2.2004 上的 minikube v1.13.0
✨  根据用户配置使用 none 驱动程序
👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=4, Memory=15873MB, Disk=40948MB) ...
ℹ️  OS release is CentOS Linux 8 (Core)
🐳  正在 Docker 19.03.13 中准备 Kubernetes v1.19.0…
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
    > kubectl.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubelet.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm: 37.30 MiB / 37.30 MiB [----------------] 100.00% 4.47 MiB p/s 8s
    > kubectl: 41.01 MiB / 41.01 MiB [---------------] 100.00% 2.90 MiB p/s 14s
    > kubelet: 104.88 MiB / 104.88 MiB [-------------] 100.00% 7.09 MiB p/s 15s
🤹  开始配置本地主机环境...

❗  The 'none' driver is designed for experts who need to integrate with an existing VM
💡  Most users should use the newer 'docker' driver instead, which does not require root!
📘  For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

❗  kubectl 和 minikube 配置将存储在 /root 中
❗  如需以您自己的用户身份使用 kubectl 或 minikube 命令，您可能需要重新定位该命令。例如，如需覆盖您的自定义设置，请运行：

    ▪ sudo mv /root/.kube /root/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

💡  此操作还可通过设置环境变量 CHANGE_MINIKUBE_NONE_USER=true 自动完成
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" by default
```

**Comment by shiguanghuxian** [comment]
换了个虚拟机可以了，可能和网络有关系，可否知道是那些域名不行，这边是否可以优化下
