### ISSUE TITLE
minikube addons enable ingress 时 镜像拉取不到 可以解决一下吗

### ISSUE THREAD

**Issue by yandou89** [AliyunContainerService/minikube#33]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by denverdino** [comment]
Fixed in v1.16.0, pls following

https://github.com/AliyunContainerService/minikube/wiki
