### ISSUE TITLE
添加节点失败

### ISSUE THREAD

**Issue by RogueCultivators** [AliyunContainerService/minikube#37]
registry.cn-hangzhou.aliyuncs.com/google_containers/kindnetd 不存在

**Comment by RogueCultivators** [comment]
![image](https://user-images.githubusercontent.com/49176713/108793877-88d81d00-75bf-11eb-924d-4b071bcac538.png)
![image](https://user-images.githubusercontent.com/49176713/108793894-92618500-75bf-11eb-956b-fe0a17bc5f17.png)

**Comment by wuyad** [comment]
我有相同的问题，你是怎么解决的？

**Comment by RogueCultivators** [comment]
可以不用管profile&nbsp; 实际是创建成功了


 
---原始邮件---
发件人: "wuya"<notifications@github.com&gt;
发送时间: 2021年3月5日 16:36:52
收件人: "AliyunContainerService/minikube"<minikube@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"RogueCultivators"<450923665@qq.com&gt;;
主题: Re: [AliyunContainerService/minikube] 添加节点失败 (#37)




 
我有相同的问题，你是怎么解决的？

**Comment by wuyad** [comment]
配置两个节点时，dashboard启不来。
kube-system   pod/kindnet-dfrg9                      0/1     ImagePullBackOff   0          3m14s
kube-system   pod/kindnet-x5zwl                      0/1     ErrImagePull       0          2m6s

**Comment by RogueCultivators** [comment]
你可以配置cni为其他的，这样就可以解决这个问题


 
---原始邮件---
发件人: "wuya"<notifications@github.com&gt;
发送时间: 2021年3月5日 17:46:16
收件人: "AliyunContainerService/minikube"<minikube@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"RogueCultivators"<450923665@qq.com&gt;;
主题: Re: [AliyunContainerService/minikube] 添加节点失败 (#37)




 
配置两个节点时，dashboard启不来。
 kube-system   pod/kindnet-dfrg9                      0/1     ImagePullBackOff   0          3m14s
 kube-system   pod/kindnet-x5zwl                      0/1     ErrImagePull       0          2m6s

**Comment by RogueCultivators** [comment]
你这个是因为镜像无法拉取的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wuya"<notifications@github.com&gt;; 
发送时间: 2021年3月5日(星期五) 下午5:46
收件人: "AliyunContainerService/minikube"<minikube@noreply.github.com&gt;; 
抄送: "450923665"<450923665@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [AliyunContainerService/minikube] 添加节点失败 (#37)





 
配置两个节点时，dashboard启不来。
 kube-system   pod/kindnet-dfrg9                      0/1     ImagePullBackOff   0          3m14s
 kube-system   pod/kindnet-x5zwl                      0/1     ErrImagePull       0          2m6s

**Comment by RogueCultivators** [comment]
具体的方法我回家给你


 
---原始邮件---
发件人: "wuya"<notifications@github.com&gt;
发送时间: 2021年3月5日 17:46:16
收件人: "AliyunContainerService/minikube"<minikube@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"RogueCultivators"<450923665@qq.com&gt;;
主题: Re: [AliyunContainerService/minikube] 添加节点失败 (#37)




 
配置两个节点时，dashboard启不来。
 kube-system   pod/kindnet-dfrg9                      0/1     ImagePullBackOff   0          3m14s
 kube-system   pod/kindnet-x5zwl                      0/1     ErrImagePull       0          2m6s

**Comment by RogueCultivators** [comment]
minikube start --network-plugin=cni --cni=calico&nbsp; 修改默认cni插件&nbsp; 即可启动成功


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AliyunContainerService/minikube"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 下午5:46
收件人:&nbsp;"AliyunContainerService/minikube"<minikube@noreply.github.com&gt;;
抄送:&nbsp;"450923665"<450923665@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [AliyunContainerService/minikube] 添加节点失败 (#37)





 
配置两个节点时，dashboard启不来。
 kube-system   pod/kindnet-dfrg9                      0/1     ImagePullBackOff   0          3m14s
 kube-system   pod/kindnet-x5zwl                      0/1     ErrImagePull       0          2m6s
