### ISSUE TITLE
环境 hyperv minikube 0.30 版本 ，电脑重启后 ipv4 丢失，只剩下 ipv6 地址 

### ISSUE THREAD

**Issue by lluck42** [AliyunContainerService/minikube#6]
start 命令

minikube.exe start --registry-mirror="https://registry.docker-cn.com" --vm-driver="hyperv" --memory=2048 --hyperv-virtual-switch="default" --mount --mount-string="d::/d"

**Comment by lluck42** [comment]
更新到v0.35发现没有这个问题了

**Comment by denverdino** [comment]
多谢，告知
