### ISSUE TITLE
coredns can not pull

### ISSUE THREAD

**Issue by jaywlm** [AliyunContainerService/minikube#70]
minikube start --registry-mirror=https://registry.docker-cn.com

error log: Unable to load cached images: loading cached images: stat /Users/wanglimiao/.minikube/cache/images/registry.cn-hangzhou.aliyuncs.com/google_containers/coredns/coredns_v1.8.4: no such file or directory

**Comment by denverdino** [comment]
使用官网最新版本 v1.24.0
```
minikube start --image-mirror-country='cn'
```
