### ISSUE TITLE
aliyun-v0.35.0 centos7 minikube start 异常

### ISSUE THREAD

**Issue by yk125123** [AliyunContainerService/minikube#9]
测试安装minikube遇到了问题，aliyun-v0.35.0 编译后，执行minikube start报错，SSH: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml 执行到这里，镜像拉取还是使用的https://k8s.gcr.io,具体执行过程如下：
`[root@bi_data_back_server` ~]# rm -rf /root/.minikube
[root@bi_data_back_server ~]# minikube start -p minikube_server_003 --registry-mirror=https://registry.docker-cn.com –-vm-driver=virtualbox  --memory=2096 --v=3  --alsologtostderr
W0319 14:10:50.512052   15668 root.go:145] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0319 14:10:50.512980   15668 notify.go:121] Checking for updates...
o   minikube v0.35.0 on linux (amd64)
I0319 14:10:51.245030   15668 start.go:582] Saving config:
{
    "MachineConfig": {
        "MinikubeISO": "https://storage.googleapis.com/minikube/iso/minikube-v0.35.0.iso",
        "Memory": 2096,
        "CPUs": 2,
        "DiskSize": 20000,
        "VMDriver": "virtualbox",
        "ContainerRuntime": "docker",
        "HyperkitVpnKitSock": "",
        "HyperkitVSockPorts": [],
        "XhyveDiskDriver": "ahci-hd",
        "DockerEnv": null,
        "InsecureRegistry": null,
        "RegistryMirror": [
            "https://registry.docker-cn.com"
        ],
        "HostOnlyCIDR": "192.168.99.1/24",
        "HypervVirtualSwitch": "",
        "KvmNetwork": "default",
        "DockerOpt": null,
        "DisableDriverMounts": false,
        "NFSShare": [],
        "NFSSharesRoot": "/nfsshares",
        "UUID": "",
        "GPU": false,
        "NoVTXCheck": false
    },
    "KubernetesConfig": {
        "KubernetesVersion": "v1.13.4",
        "NodeIP": "",
        "NodePort": 8443,
        "NodeName": "minikube",
        "APIServerName": "minikubeCA",
        "APIServerNames": null,
        "APIServerIPs": null,
        "DNSDomain": "cluster.local",
        "ContainerRuntime": "docker",
        "CRISocket": "",
        "NetworkPlugin": "",
        "FeatureGates": "",
        "ServiceCIDR": "10.96.0.0/12",
        "ExtraOptions": null,
        "ShouldLoadCachedImages": false,
        "EnableDefaultCNI": false
    }
}
I0319 14:10:51.246068   15668 cluster.go:70] Machine does not exist... provisioning new machine
I0319 14:10:51.246110   15668 cluster.go:71] Provisioning machine with config: {MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v0.35.0.iso Memory:2096 CPUs:2 DiskSize:20000 VMDriver:virtualbox ContainerRuntime:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] XhyveDiskDriver:ahci-hd DockerEnv:[] InsecureRegistry:[] RegistryMirror:[https://registry.docker-cn.com] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: KvmNetwork:default Downloader:{} DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: GPU:false NoVTXCheck:false}
>   Creating virtualbox VM (CPUs=2, Memory=2096MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
 184.42 MB / 184.42 MB [============================================] 100.00% 0s
Creating CA: /root/.minikube/certs/ca.pem
Creating client certificate: /root/.minikube/certs/cert.pem
Downloading /root/.minikube/cache/boot2docker.iso from file:///root/.minikube/cache/iso/minikube-v0.35.0.iso...
Creating VirtualBox VM...
Creating SSH key...
Starting the VM...
Check network to re-create if needed...
Waiting for an IP...
I0319 14:12:11.440965   15668 ssh_runner.go:101] SSH: sudo rm -f /etc/docker/server-key.pem
I0319 14:12:11.446728   15668 ssh_runner.go:101] SSH: sudo mkdir -p /etc/docker
I0319 14:12:11.458184   15668 ssh_runner.go:101] SSH: sudo rm -f /etc/docker/ca.pem
I0319 14:12:11.463265   15668 ssh_runner.go:101] SSH: sudo mkdir -p /etc/docker
I0319 14:12:11.474916   15668 ssh_runner.go:101] SSH: sudo rm -f /etc/docker/server.pem
I0319 14:12:11.479571   15668 ssh_runner.go:101] SSH: sudo mkdir -p /etc/docker
Setting Docker configuration on the remote daemon...
-   "minikube_server_003" IP address is 192.168.99.102
I0319 14:12:12.010546   15668 start.go:582] Saving config:
{
    "MachineConfig": {
        "MinikubeISO": "https://storage.googleapis.com/minikube/iso/minikube-v0.35.0.iso",
        "Memory": 2096,
        "CPUs": 2,
        "DiskSize": 20000,
        "VMDriver": "virtualbox",
        "ContainerRuntime": "docker",
        "HyperkitVpnKitSock": "",
        "HyperkitVSockPorts": [],
        "XhyveDiskDriver": "ahci-hd",
        "DockerEnv": null,
        "InsecureRegistry": null,
        "RegistryMirror": [
            "https://registry.docker-cn.com"
        ],
        "HostOnlyCIDR": "192.168.99.1/24",
        "HypervVirtualSwitch": "",
        "KvmNetwork": "default",
        "DockerOpt": null,
        "DisableDriverMounts": false,
        "NFSShare": [],
        "NFSSharesRoot": "/nfsshares",
        "UUID": "",
        "GPU": false,
        "NoVTXCheck": false
    },
    "KubernetesConfig": {
        "KubernetesVersion": "v1.13.4",
        "NodeIP": "192.168.99.102",
        "NodePort": 8443,
        "NodeName": "minikube",
        "APIServerName": "minikubeCA",
        "APIServerNames": null,
        "APIServerIPs": null,
        "DNSDomain": "cluster.local",
        "ContainerRuntime": "docker",
        "CRISocket": "",
        "NetworkPlugin": "",
        "FeatureGates": "",
        "ServiceCIDR": "10.96.0.0/12",
        "ExtraOptions": null,
        "ShouldLoadCachedImages": false,
        "EnableDefaultCNI": false
    }
}
-   Configuring Docker as the container runtime ...
I0319 14:12:12.025357   15668 ssh_runner.go:101] SSH: systemctl is-active --quiet service containerd
I0319 14:12:12.031278   15668 ssh_runner.go:101] SSH: sudo systemctl stop containerd
I0319 14:12:12.041675   15668 ssh_runner.go:101] SSH: systemctl is-active --quiet service containerd
I0319 14:12:12.049553   15668 ssh_runner.go:101] SSH: systemctl is-active --quiet service crio
I0319 14:12:12.054823   15668 ssh_runner.go:101] SSH: sudo systemctl stop crio
I0319 14:12:12.071620   15668 ssh_runner.go:101] SSH: systemctl is-active --quiet service crio
I0319 14:12:12.077367   15668 ssh_runner.go:101] SSH: systemctl is-active --quiet service rkt-api
I0319 14:12:12.083119   15668 ssh_runner.go:101] SSH: sudo systemctl stop rkt-api
I0319 14:12:12.094244   15668 ssh_runner.go:101] SSH: sudo systemctl stop rkt-metadata
I0319 14:12:12.105508   15668 ssh_runner.go:101] SSH: systemctl is-active --quiet service rkt-api
I0319 14:12:12.112980   15668 ssh_runner.go:101] SSH: sudo systemctl restart docker
-   Preparing Kubernetes environment ...
I0319 14:12:12.465137   15668 kubeadm.go:394] kubelet v1.13.4 config:

[Unit]
Wants=docker.socket

[Service]
ExecStart=
ExecStart=/usr/bin/kubelet --allow-privileged=true --cluster-dns=10.96.0.10 --authorization-mode=Webhook --client-ca-file=/var/lib/minikube/certs/ca.crt --container-runtime=docker --fail-swap-on=false --pod-manifest-path=/etc/kubernetes/manifests --hostname-override=minikube --cluster-domain=cluster.local --cgroup-driver=cgroupfs --kubeconfig=/etc/kubernetes/kubelet.conf --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf

[Install]
@   Downloading kubelet v1.13.4
@   Downloading kubeadm v1.13.4
I0319 14:12:17.211215   15668 ssh_runner.go:101] SSH: sudo rm -f /usr/bin/kubeadm
I0319 14:12:17.219408   15668 ssh_runner.go:101] SSH: sudo mkdir -p /usr/bin
I0319 14:12:22.611228   15668 ssh_runner.go:101] SSH: sudo rm -f /usr/bin/kubelet
I0319 14:12:22.619981   15668 ssh_runner.go:101] SSH: sudo mkdir -p /usr/bin
I0319 14:12:24.619605   15668 ssh_runner.go:101] SSH: sudo rm -f /lib/systemd/system/kubelet.service
I0319 14:12:24.624250   15668 ssh_runner.go:101] SSH: sudo mkdir -p /lib/systemd/system
I0319 14:12:24.633962   15668 ssh_runner.go:101] SSH: sudo rm -f /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
I0319 14:12:24.638796   15668 ssh_runner.go:101] SSH: sudo mkdir -p /etc/systemd/system/kubelet.service.d
I0319 14:12:24.648379   15668 ssh_runner.go:101] SSH: sudo rm -f /var/lib/kubeadm.yaml
I0319 14:12:24.653603   15668 ssh_runner.go:101] SSH: sudo mkdir -p /var/lib
I0319 14:12:24.665162   15668 ssh_runner.go:101] SSH: sudo rm -f /etc/kubernetes/addons/storage-provisioner.yaml
I0319 14:12:24.669881   15668 ssh_runner.go:101] SSH: sudo mkdir -p /etc/kubernetes/addons
I0319 14:12:24.679714   15668 ssh_runner.go:101] SSH: sudo rm -f /etc/kubernetes/manifests/addon-manager.yaml
I0319 14:12:24.684295   15668 ssh_runner.go:101] SSH: sudo mkdir -p /etc/kubernetes/manifests/
I0319 14:12:24.698077   15668 ssh_runner.go:101] SSH: sudo rm -f /etc/kubernetes/addons/storageclass.yaml
I0319 14:12:24.702692   15668 ssh_runner.go:101] SSH: sudo mkdir -p /etc/kubernetes/addons
I0319 14:12:24.712282   15668 ssh_runner.go:101] SSH:
sudo systemctl daemon-reload &&
sudo systemctl enable kubelet &&
sudo systemctl start kubelet
I0319 14:12:24.780915   15668 utils.go:224] ! Created symlink /etc/systemd/system/multi-user.target.wants/kubelet.service → /usr/lib/systemd/system/kubelet.service.
I0319 14:12:24.854858   15668 certs.go:47] Setting up certificates for IP: 192.168.99.102
I0319 14:12:26.212371   15668 ssh_runner.go:101] SSH: sudo rm -f /var/lib/minikube/certs/ca.crt
I0319 14:12:26.220249   15668 ssh_runner.go:101] SSH: sudo mkdir -p /var/lib/minikube/certs/
I0319 14:12:26.230756   15668 ssh_runner.go:101] SSH: sudo rm -f /var/lib/minikube/certs/ca.key
I0319 14:12:26.235811   15668 ssh_runner.go:101] SSH: sudo mkdir -p /var/lib/minikube/certs/
I0319 14:12:26.246103   15668 ssh_runner.go:101] SSH: sudo rm -f /var/lib/minikube/certs/apiserver.crt
I0319 14:12:26.251145   15668 ssh_runner.go:101] SSH: sudo mkdir -p /var/lib/minikube/certs/
I0319 14:12:26.262103   15668 ssh_runner.go:101] SSH: sudo rm -f /var/lib/minikube/certs/apiserver.key
I0319 14:12:26.266796   15668 ssh_runner.go:101] SSH: sudo mkdir -p /var/lib/minikube/certs/
I0319 14:12:26.277463   15668 ssh_runner.go:101] SSH: sudo rm -f /var/lib/minikube/certs/proxy-client-ca.crt
I0319 14:12:26.282585   15668 ssh_runner.go:101] SSH: sudo mkdir -p /var/lib/minikube/certs/
I0319 14:12:26.293006   15668 ssh_runner.go:101] SSH: sudo rm -f /var/lib/minikube/certs/proxy-client-ca.key
I0319 14:12:26.297587   15668 ssh_runner.go:101] SSH: sudo mkdir -p /var/lib/minikube/certs/
I0319 14:12:26.309248   15668 ssh_runner.go:101] SSH: sudo rm -f /var/lib/minikube/certs/proxy-client.crt
I0319 14:12:26.314110   15668 ssh_runner.go:101] SSH: sudo mkdir -p /var/lib/minikube/certs/
I0319 14:12:26.324054   15668 ssh_runner.go:101] SSH: sudo rm -f /var/lib/minikube/certs/proxy-client.key
I0319 14:12:26.328820   15668 ssh_runner.go:101] SSH: sudo mkdir -p /var/lib/minikube/certs/
I0319 14:12:26.339172   15668 ssh_runner.go:101] SSH: sudo rm -f /var/lib/minikube/kubeconfig
I0319 14:12:26.344304   15668 ssh_runner.go:101] SSH: sudo mkdir -p /var/lib/minikube
I0319 14:12:26.704772   15668 config.go:125] Using kubeconfig:  /root/.kube/config
-   Pulling images required by Kubernetes v1.13.4 ...
I0319 14:12:26.706655   15668 ssh_runner.go:101] SSH: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
I0319 14:12:41.876841   15668 utils.go:224] ! failed to pull image "k8s.gcr.io/kube-apiserver:v1.13.4": output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
I0319 14:12:41.876908   15668 utils.go:224] ! , error: exit status 1
X   Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout:
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.13.4": output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
: Process exited with status 1
-   Launching Kubernetes v1.13.4 using kubeadm ...
I0319 14:12:41.878862   15668 ssh_runner.go:137] Run with output:
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap `--ignore-preflight-errors=CRI`

**Comment by denverdino** [comment]
我重新推送了K8s的包，这边测试是成功的

**Comment by denverdino** [comment]
```
$ minikube start --registry-mirror=https://registry.docker-cn.com
😄  minikube v0.35.0 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 184.42 MB / 184.42 MB [============================================] 100.00% 0s
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.13.4
💾  Downloading kubelet v1.13.4
🚜  Pulling images required by Kubernetes v1.13.4 ...
🚀  Launching Kubernetes v1.13.4 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller addon-manager dns
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
$ minikube dashboard
🔌  Enabling dashboard ...
🤔  Verifying dashboard health ...
🚀  Launching proxy ...
🤔  Verifying proxy health ...
```

**Comment by denverdino** [comment]
请重新验证，多谢

**Comment by yk125123** [comment]
十分感谢，昨天晚上回去后重新验证了下，原环境中依然失败，重新初始化了一个centos7.6 环境，安装docker、go环境，下载v0.35.0源码编译后，minikube start  可以了，是我这边的问题。
 没弄明白之前为什么会一致失败，k8s这块刚接触，学习被卡在这初始化，有些着急了

**Comment by denverdino** [comment]
昨天修正了几个问题，感谢您的耐心
